### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by supraditya** [AnveshakR/Automatic-Water-Level-Balancer#1]
In readme, what is 'prject'
utter nonsense I say

**Comment by AnveshakR** [comment]
I deeply apologise for the grammatical mistake I seem to have committed in the README.md file I have uploaded on GitHub for my Automatic Water Level Balancer project. 
You can be assured that I shall push a commit rectifying this grave and heinous error that I have made at the earliest. 
I wholeheartedly thank you for bringing this unpardonable error to my notice, and I shall do my best to fix it at the earliest. Nevertheless, I ask that you find it in your heart to forgive me for this misdeed.

**Comment by supraditya** [comment]
I completely understand the grammatical shortcomings from my time knowing you and thus pardon you for the same. Make sure it doesn't happen again 😤
